package Entities

import com.googlecode.mapperdao.{Entity, SurrogateIntId, ValuesMap}
import model.Tweet

object TweetEntity extends Entity[Int, SurrogateIntId, Tweet] {
  val id = key("id") autogenerated (_.id)
  val contents = column("contents") to (_.contents)
  val tweetedAt = column("tweetedAt") to (_.tweetedAt)

  def constructor(implicit m: ValuesMap) = new Tweet(id, contents, tweetedAt) with Stored

}
